dist: bionic

language: php

services:
  - postgresql

addons:
  sonarcloud:
    organization: "chubbyphp"

git:
  depth: false

env:
  global:
    - APP_ENV=phpunit
    - DATABASE_USER=postgres
    - DATABASE_PASS=
    - DATABASE_HOST=127.0.0.1
    - DATABASE_PORT=5432
    - DATABASE_NAME=petstore

matrix:
  include:
    - php: 7.4
    - php: 8.0

before_script:
  - echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini
  - (phpenv config-rm xdebug.ini || exit 0)
  - pecl install pcov
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer update $composerargs -n

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=build/phpunit/clover.xml --json_path=build/coveralls.json -v
  - sonar-scanner
