version: '3.0'
services:
  php:
    container_name: petstore-php
    hostname: petstore-php
    build:
      dockerfile: ./dev/php/Dockerfile
      context: ./docker
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      APP_ENV: dev
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_HOST: postgres
      DATABASE_NAME: petstore
      DATABASE_PORT: 5432
      SSH_AUTH_SOCK: /ssh-agent
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
    volumes:
      - ./:/var/www/html
      - ~/.bash_aliases:/var/www/.bash_aliases
      - ~/.bash_history:/var/www/.bash_history
      - ~/.gitconfig:/var/www/.gitconfig
      - ~/.gitignore:/var/www/.gitignore
      - ~/.zsh_aliases:/var/www/.zsh_aliases
      - ~/.zsh_history:/var/www/.zsh_history
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  blackfire:
    container_name: petstore-blackfire
    hostname: petstore-blackfire
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
  postgres:
    container_name: petstore-postgres
    hostname: pestore-postgres
    image: postgres:13
    command: -c log_statement=all -c log_error_verbosity=VERBOSE
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '15432:5432'
  nginx:
    container_name: petstore-nginx
    hostname: petstore-nginx
    build:
      dockerfile: ./dev/nginx/Dockerfile
      context: ./docker
    ports:
      - '10080:80'
      - '10443:443'
    volumes:
      - ./:/var/www/html:ro
    depends_on:
      - php
  elasticsearch:
    container_name: petstore-elasticsearch
    hostname: petstore-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms128m -Xmx128m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '19200:9200'
  kibana:
    container_name: petstore-kibana
    hostname: petstore-kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - '15601:5601'
    depends_on:
      - elasticsearch
  filebeat:
    container_name: petstore-filebeat
    hostname: petstore-filebeat
    image: docker.elastic.co/beats/filebeat:7.9.2
    command: --strict.perms=false
    user: root
    volumes:
      - ./docker/prod/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./var/log/dev:/var/log/application:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - kibana
