version: '3.0'
services:
  php:
    container_name: petstore-php
    hostname: petstore-php
    build:
      dockerfile: ./dev/php/Dockerfile
      context: ./docker
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    labels:
      co.elastic.logs/fileset.stderr: error
    environment:
      APP_ENV: dev
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_HOST: postgres
      DATABASE_NAME: petstore
      DATABASE_PORT: 5432
      SSH_AUTH_SOCK: /ssh-agent
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
    volumes:
      - ./:/var/www/html
      - ~/.bash_aliases:/var/www/.bash_aliases
      - ~/.bash_history:/var/www/.bash_history
      - ~/.gitconfig:/var/www/.gitconfig
      - ~/.gitignore:/var/www/.gitignore
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - postgres
  blackfire:
    container_name: petstore-blackfire
    hostname: petstore-blackfire
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
  postgres:
    container_name: petstore-postgres
    hostname: pestore-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '15432:5432'
  nginx:
    container_name: petstore-nginx
    hostname: petstore-nginx
    image: nginx:1.17.8
    labels:
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    ports:
      - '10080:80'
      - '10443:443'
    volumes:
      - ./docker/prod/nginx/certificate_key:/etc/nginx/certificate_key:ro
      - ./docker/prod/nginx/certificate:/etc/nginx/certificate:ro
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - php
  elasticsearch:
    container_name: petstore-elasticsearch
    hostname: petstore-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms128m -Xmx128m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '19200:9200'
  kibana:
    container_name: petstore-kibana
    hostname: petstore-kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - '15601:5601'
    depends_on:
      - elasticsearch
  filebeat:
    container_name: petstore-filebeat
    hostname: petstore-filebeat
    image: docker.elastic.co/beats/filebeat:7.5.2
    user: root
    volumes:
      - ./docker/prod/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/var/www/html:ro
    depends_on:
      - elasticsearch
      - kibana
